### PR TITLE
Burakcan june8

### PR DESCRIPTION
**Pull request by burakcankazim**
Arranged to comply with the  new structure. 
Refactored AnimeAPI.
Frontend with AnimeUI.
Dockerfile's for both backend and frontend with a docker-compose file.

### CODE REVIEW

**Review by veyisTurgut — APPROVED** [review]
This is very similar to the [previous pr](https://github.com/bounswe/2021SpringGroup12/pull/139). Difference is helpers and Dockerfiles, I presume. Since you checked out from my branch, I know the code. Approved.

**Comment by gokayyildiz** [comment]
/usr/src/app/./sqlfiles/practice-app.db
is this the final database location that we used in docker

**Comment by veyisTurgut** [comment]
> /usr/src/app/./sqlfiles/practice-app.db
> is this the final database location that we used in docker

We mount our files under /usr/src/app.
sqlfiles folder is in the current folder.
So, I guess either this or " /usr/src/app/sqlfiles/practice-app.db"

**Comment by burakcankazim** [comment]
> /usr/src/app/./sqlfiles/practice-app.db
> is this the final database location that we used in docker

Yes, absolute path of the db file in docker is that.

**Comment by batuhanovski** [comment]
It looks fine to me.

**Review by batuhanovski — APPROVED** [review]
It looks fine to me

**Pull request merged**
