### PR TITLE
added name surname fields to signup endpoint

### LINKED ISSUE #489: Adding name and surname fields for sign-in
**Description**
-Name and surname fields will be added to backend according to requirement: Guests shall enter their e-mail, name, surname, username and a password in order to sign up.

### PR DESCRIPTION
**Pull request by veyisTurgut**
Implements #489 

* Old json body: `{
  "email": "veyis@mail.tr",
  "password": "very_strong_password",
  "username": "veyist"
}`

* New json body: `{
  "email": "veyis@mail.tr",
  "password": "very_strong_password",
  "username": "veyist",
  "name": "veyis",
  "surname":"turgut"
}`

### CODE REVIEW

**Comment by veyisTurgut** [comment]
Fixes #490

**Comment by burakcankazim** [comment]
> Implements #489
> 
>     * Old json body: `{ "email": "veyis@mail.tr", "password": "very_strong_password", "username": "veyist" }`
> 
>     * New json body: `{ "email": "veyis@mail.tr", "password": "very_strong_password", "username": "veyist", "name": "veyis", "surname":"turgut" }`

Everything is ok about this implementation.

**Comment by burakcankazim** [comment]
> Implements #490

Everything about this seems ok too but isn't using same branch and pr for both of them a little bit confusing?

**Comment by veyisTurgut** [comment]
Yeah, it is. Since it was just a few lines of code, I been lazy :p

**Pull request merged**
