### PR TITLE
fix(backend): fixed missing group goal method #385

### PR DESCRIPTION
**Pull request by burakcankazim**

### CODE REVIEW

**Comment by veyisTurgut** [comment]
@burakcankazim let's merge this. But I couldn't decide what to do with conflict. Is that function useful or not? Can you merge this?

**Comment by burakcankazim** [comment]
> @burakcankazim let's merge this. But I couldn't decide what to do with conflict. Is that function useful or not? Can you merge this?

Yes I think it was used by the frontend teams at some point, we should include it for the sake of backward compatability.

**Comment by burakcankazim** [comment]
Resolved the conflict can be merged any time.

**Comment by veyisTurgut** [comment]
I can't merge this until it passes checks. @burakcankazim

**Comment by burakcankazim** [comment]
@veyisTurgut Reset this branch to current dev/backend since the old branch was too old to merge smoothly, then cherrypicked the fixes from the old branch to new branch. This should work as far as I know.

**Review by veyisTurgut — APPROVED** [review]
Great!

**Pull request merged**
